### ISSUE TITLE
see the Excel file

### ISSUE THREAD

**Issue by hczyni** [giaminhgist/3D-DAM#1]
Dear AI developer, I'd like to see the Excel file you used in your project! Thank you!

**Comment by giaminhgist** [comment]
Hi. There is one example of the excel file for my project:
https://docs.google.com/spreadsheets/d/1fCEE2txoEreD0LJ-J8yF_8YgmaKanqbA/edit?usp=sharing&ouid=108808973845825811261&rtpof=true&sd=true
