### ISSUE TITLE
Hello, this is the research area I am currently working on. Do you have any datasets that you can provide me for learning? Thank you very much.

### ISSUE THREAD

**Issue by xuruishu** [giaminhgist/3D-DAM#2]
Hello, this is the research area I am currently working on. Do you have any datasets that you can provide me for learning? Thank you very much.

**Comment by giaminhgist** [comment]
Hello. There are several public databases that you could use such as ADNI, AIBL, and OASIS, etc.
ADNI and AIBL:
https://ida.loni.usc.edu/login.jsp
OASIS:
https://www.oasis-brains.org/
